# Google Cloud Build configuration for SpeakEasy Web Frontend
# This file automates deployment of the web app to Cloud Run

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.web'
      - '-t'
      - 'gcr.io/$PROJECT_ID/speakeasy-web:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/speakeasy-web:latest'
      - '.'

  # Push the images to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/speakeasy-web:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/speakeasy-web:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'speakeasy-web'
      - '--image'
      - 'gcr.io/$PROJECT_ID/speakeasy-web:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '80'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '100'

# Images to store in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/speakeasy-web:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/speakeasy-web:latest'

# Options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'
