# SpeakEasy Full Stack - Docker Compose
# For local development and testing

version: '3.8'

services:
  # Ollama LLM Server
  ollama:
    build: .
    container_name: speakeasy-llm
    ports:
      - "11434:11434"
    volumes:
      # Persist models to avoid re-downloading
      - ollama-models:/root/.ollama/models
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_NUM_PARALLEL=2
      - OLLAMA_MAX_LOADED_MODELS=2
    restart: unless-stopped
    # GPU support (uncomment if you have NVIDIA GPU with Docker GPU support)
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5m

  # Backend API Server
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: speakeasy-backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - NODE_ENV=development
      - OLLAMA_URL=http://ollama:11434
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      ollama:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Web Frontend
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: speakeasy-web
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  ollama-models:
    driver: local

networks:
  default:
    name: speakeasy-network
