# SpeakEasy LLM Server - Docker Compose
# For local development and testing

version: '3.8'

services:
  ollama:
    build: .
    container_name: speakeasy-llm
    ports:
      - "11434:11434"
    volumes:
      # Persist models to avoid re-downloading
      - ollama-models:/root/.ollama/models
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_NUM_PARALLEL=2
      - OLLAMA_MAX_LOADED_MODELS=2
    restart: unless-stopped
    # GPU support (uncomment if you have NVIDIA GPU with Docker GPU support)
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5m

volumes:
  ollama-models:
    driver: local
