#!/bin/bash

echo "🚀 Setting up Auto-Deploy for SpeakEasy Web App"
echo "================================================"
echo ""
echo "To enable automatic deployment when you push to GitHub,"
echo "you need to connect your GitHub repository to Google Cloud Build."
echo ""
echo "📋 Steps to complete setup:"
echo ""
echo "1. Open Cloud Build Triggers:"
echo "   https://console.cloud.google.com/cloud-build/triggers?project=modular-analog-476221-h8"
echo ""
echo "2. Click 'CREATE TRIGGER'"
echo ""
echo "3. Connect your repository:"
echo "   - Select 'GitHub (Cloud Build GitHub App)'"
echo "   - Click 'CONNECT NEW REPOSITORY'"
echo "   - Authenticate with GitHub"
echo "   - Select repository: theoadoree/speakeasy"
echo "   - Click 'CONNECT'"
echo ""
echo "4. Configure the trigger:"
echo "   Name: deploy-web-on-push"
echo "   Description: Auto-deploy web app to Cloud Run on push to main"
echo "   Event: Push to a branch"
echo "   Branch: ^main$"
echo "   Configuration: Cloud Build configuration file (yaml or json)"
echo "   Location: Repository"
echo "   Cloud Build configuration file location: /cloudbuild-web.yaml"
echo ""
echo "5. Click 'CREATE'"
echo ""
echo "✅ Once setup is complete, every push to main will automatically:"
echo "   • Build the Expo web app"
echo "   • Create a Docker image"
echo "   • Deploy to Cloud Run"
echo "   • Update https://speakeasy-ai.app"
echo ""
echo "📝 The cloudbuild-web.yaml file has already been created for you!"
echo ""
