#!/bin/bash

# Create OAuth 2.0 credentials for SpeakEasy
PROJECT_ID="modular-analog-476221-h8"
DOMAIN="speakeasy-ai.app"
CLOUD_RUN_URL="https://speakeasy-web-823510409781.us-central1.run.app"

echo "🔐 Google OAuth 2.0 Setup for SpeakEasy"
echo "========================================"
echo ""
echo "Project ID: $PROJECT_ID"
echo "Domain: $DOMAIN"
echo "Cloud Run URL: $CLOUD_RUN_URL"
echo ""
echo "📋 Step-by-Step Instructions:"
echo ""
echo "1. 🌐 Open Google Cloud Console:"
echo "   https://console.cloud.google.com/apis/credentials?project=$PROJECT_ID"
echo ""
echo "2. 🔑 Create OAuth 2.0 Client ID:"
echo "   - Click 'Create Credentials' > 'OAuth 2.0 Client IDs'"
echo "   - Choose 'Web application'"
echo "   - Name: 'SpeakEasy Web App'"
echo ""
echo "3. 🌍 Add Authorized Origins:"
echo "   - $DOMAIN"
echo "   - $CLOUD_RUN_URL"
echo ""
echo "4. 🔄 Add Authorized Redirect URIs:"
echo "   - $DOMAIN"
echo "   - $CLOUD_RUN_URL"
echo ""
echo "5. 📋 Copy the Client ID and update:"
echo "   - Replace GOOGLE_CLIENT_ID in web/index.html"
echo "   - Set environment variable in Cloud Run"
echo ""
echo "🍎 Apple Sign In Setup:"
echo "======================"
echo ""
echo "1. 🌐 Open Apple Developer Console:"
echo "   https://developer.apple.com/account/resources/identifiers/list"
echo ""
echo "2. 📱 Create App ID:"
echo "   - Bundle ID: com.speakeasy.app"
echo "   - Enable 'Sign In with Apple'"
echo ""
echo "3. 🔧 Create Service ID:"
echo "   - Identifier: com.speakeasy.web"
echo "   - Enable 'Sign In with Apple'"
echo "   - Primary App ID: com.speakeasy.app"
echo "   - Domains: $DOMAIN"
echo "   - Return URLs: https://$DOMAIN"
echo ""
echo "4. 🔑 Create Private Key:"
echo "   - Go to Keys > Sign In with Apple"
echo "   - Download .p8 key file"
echo "   - Note Key ID and Team ID"
echo ""
echo "⚙️ Environment Variables:"
echo "========================="
echo ""
echo "gcloud run services update speakeasy-backend \\"
echo "  --region=us-central1 \\"
echo "  --set-env-vars=\"GOOGLE_CLIENT_ID=YOUR_GOOGLE_CLIENT_ID\""
echo ""
echo "🎯 Quick Test:"
echo "============="
echo "1. Complete the setup above"
echo "2. Visit: https://$DOMAIN"
echo "3. Try 'Continue with Google' and 'Continue with Apple'"
echo "4. Check browser console for any errors"
echo ""
echo "📞 Need Help?"
echo "============="
echo "Check the OAUTH_SETUP.md file for detailed instructions"
