steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/modular-analog-476221-h8/speakeasy-backend:latest'
      - '.'

  # Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/modular-analog-476221-h8/speakeasy-backend:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'speakeasy-backend'
      - '--image'
      - 'gcr.io/modular-analog-476221-h8/speakeasy-backend:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      # Use Google Cloud Secret Manager for sensitive values
      # Set secrets via: gcloud run services update speakeasy-backend --update-secrets=OPENAI_API_KEY=openai-api-key:latest
      - '--update-env-vars'
      - 'GOOGLE_CLIENT_ID=823510409781-s5d3hrffelmjcl8kjvchcv3tlbp0shbo.apps.googleusercontent.com,APPLE_TEAM_ID=E7B9UE64SF,APPLE_CLIENT_ID=com.speakeasy.webapp,APPLE_KEY_ID=864SJW3HGZ'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '60s'

# Images to store in Container Registry
images:
  - 'gcr.io/modular-analog-476221-h8/speakeasy-backend:latest'

# Options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'


