steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/modular-analog-476221-h8/speakeasy-backend:latest'
      - '.'

  # Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/modular-analog-476221-h8/speakeasy-backend:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'speakeasy-backend'
      - '--image'
      - 'gcr.io/modular-analog-476221-h8/speakeasy-backend:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      # Public configuration (not secrets)
      - '--set-env-vars'
      - 'NODE_ENV=production,APPLE_TEAM_ID=E7B9UE64SF,APPLE_CLIENT_ID=com.speakeasy.webapp,APPLE_KEY_ID=864SJW3HGZ,FIREBASE_PROJECT_ID=modular-analog-476221-h8'
      # Mount secrets from Secret Manager
      - '--update-secrets'
      - 'OPENAI_API_KEY=openai-api-key:latest,APPLE_PRIVATE_KEY_BASE64=apple-private-key:latest,JWT_SECRET=jwt-secret:latest'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '60s'

# Images to store in Container Registry
images:
  - 'gcr.io/modular-analog-476221-h8/speakeasy-backend:latest'

# Options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'


