# Uncomment the next line to define a global platform for your project
platform :ios, '17.0'

target 'SpeakEasy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SpeakEasy
  pod 'GoogleSignIn', '~> 7.0'

end
