name: Build Mobile Apps (iOS & Android)

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - ios
          - android
      profile:
        description: 'Build profile'
        required: true
        default: 'production'
        type: choice
        options:
          - development
          - preview
          - production
          - production-store

jobs:
  build-ios:
    name: Build iOS
    runs-on: ubuntu-latest
    if: github.event.inputs.platform == 'ios' || github.event.inputs.platform == 'all' || github.event_name != 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Set up Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build iOS app
        run: |
          PROFILE=${{ github.event.inputs.profile || 'production' }}
          eas build --platform ios --profile $PROFILE --non-interactive --no-wait

  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    if: github.event.inputs.platform == 'android' || github.event.inputs.platform == 'all' || github.event_name != 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Set up Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build Android app
        run: |
          PROFILE=${{ github.event.inputs.profile || 'production' }}
          eas build --platform android --profile $PROFILE --non-interactive --no-wait

  notify:
    name: Notify Build Status
    runs-on: ubuntu-latest
    needs: [build-ios, build-android]
    if: always()

    steps:
      - name: Build summary
        run: |
          echo "### Mobile Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- iOS Build: ${{ needs.build-ios.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- Android Build: ${{ needs.build-android.result }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Check [Expo dashboard](https://expo.dev) for build details" >> $GITHUB_STEP_SUMMARY
