name: Deploy Web to Cloud Run

on:
  push:
    branches: [ ci/deploy-web ]
    paths:
      - 'src/**'
      - 'vite.config.mjs'
      - 'Dockerfile'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/deploy-web.yml'

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: modular-analog-476221-h8
  REGION: us-central1
  SERVICE: speakeasy-web
  VITE_BACKEND_URL: https://speakeasy-backend-823510409781.us-central1.run.app

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/823510409781/locations/global/workloadIdentityPools/gh-oidc-pool/providers/gh-provider
          service_account: gh-actions-cloudrun@${{ env.PROJECT_ID }}.iam.gserviceaccount.com
          project_id: ${{ env.PROJECT_ID }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build web (Vite)
        env:
          VITE_BACKEND_URL: ${{ env.VITE_BACKEND_URL }}
          EXPO_PUBLIC_BACKEND_URL: ${{ env.VITE_BACKEND_URL }}
          REACT_APP_API_URL: ${{ env.VITE_BACKEND_URL }}
        run: npm run build:web

      - name: Deploy to Cloud Run
        env:
          VITE_BACKEND_URL: ${{ env.VITE_BACKEND_URL }}
        run: |
          gcloud run deploy $SERVICE \
            --source . \
            --use-docker \
            --region $REGION \
            --project $PROJECT_ID \
            --allow-unauthenticated \
            --set-build-env-vars=VITE_BACKEND_URL=${VITE_BACKEND_URL}
