name: Deploy Web App to Google Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'App.js'
      - 'index.js'
      - 'package.json'
      - 'app.json'
      - 'Dockerfile.web'
      - 'nginx.conf'
      - 'web/**'
      - '.github/workflows/deploy-web.yml'
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1
  SERVICE_NAME: speakeasy-web

jobs:
  deploy:
    name: Deploy Web App
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: |
          docker build -f Dockerfile.web \
                       -t gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA \
                       -t gcr.io/$PROJECT_ID/$SERVICE_NAME:latest \
                       .

      - name: Push Docker image to GCR
        run: |
          docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA
          docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated \
            --port 80 \
            --memory 512Mi \
            --cpu 1 \
            --min-instances 0 \
            --max-instances 100

      - name: Get service URL
        id: get-url
        run: |
          SERVICE_URL=$(gcloud run services describe $SERVICE_NAME \
            --region $REGION \
            --format 'value(status.url)')
          echo "url=$SERVICE_URL" >> $GITHUB_OUTPUT
          echo "Web app deployed to: $SERVICE_URL"

      - name: Map custom domain (if configured)
        if: github.ref == 'refs/heads/main'
        run: |
          gcloud run domain-mappings create \
            --service $SERVICE_NAME \
            --domain speakeasy-ai.app \
            --region $REGION || echo "Domain mapping may already exist"

      - name: Test deployment
        run: |
          sleep 10
          curl -f ${{ steps.get-url.outputs.url }}/health || exit 1
